# Linters to be enabled
linters:
  enable:
    - govet # Detects suspicious constructs and potential bugs in the code
    - gocyclo # Measures the complexity of functions (prevents overly complex functions)
    - ineffassign # Detects assignments to variables that are never used
    - errcheck # Ensures that errors are checked in the code (important for web apps interacting with databases or external services)
    - gosec # Detects security vulnerabilities in the code (e.g., hardcoded credentials, unsafe API usage)
    - staticcheck # Performs static analysis and checks for various issues like unused variables
    - unparam # Detects function parameters that are not used in the function
    - gci # Checks if code and import statements are formatted, with additional rules
    - lll # Enforces line length limits for better readability
    - depguard # Go linter that checks if package imports are in a list of acceptable packages
    - errorlint # Errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13
    - unused # Checks Go code for unused constants, variables, functions and types

  # Linters to be disabled (can be turned off based on project needs)
  disable:
    - gosimple # Can be disabled if the simplification rules are too aggressive

  # Performance settings for faster linting (useful for large projects)
  fast: true

  # Linters' specific settings
linters-settings:
  gocyclo:
    min-complexity: 15 # Minimum cyclomatic complexity for a function to be considered complex (default: 15)
  # errcheck:
  #   exclude:
  #     - .*_test\.go # Exclude test files from error checking, as they often involve expected errors
  gosec:
    severity: "medium" # Set minimum severity for security vulnerabilities to "medium"
  lll:
    line-length: 150 # Set the maximum line length to 150 characters

issues:
  # Files and directories to exclude from linting
  exclude:
    - vendor/ # Exclude the 'vendor' directory that contains third-party dependencies
    - .*_test\.go # Exclude test files from linting checks
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck

# General run settings
run:
  timeout: 5m # Maximum time allowed for linting to run
  tests: false # Skip linting on test files by default
